
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:pismo-test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    com.deividlm: TRACE
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
server:
   port: 8081